#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!



Contrapositive
   Definition:
      A proposition formed by contradicting both the subject and predicate or both the hypothesis and conclusion
      of a given proposition or theorem and interchanging them.
   Explanation:
      To find the contrapositive switch the hyptothesis and conclusion of a conditional statement and negating both.
   Example:
      If I first say "If it is raining then the grass is wet" then the contrapositive is 
      "If the grass is not wet then it is not raining".
   Test Question:
      If a statement is true is the contrapositive also true? And vice versa? 


Converse
   Definition:
      A converse is the result of reverseing a conditional statements two parts.
   Explanation:
      Switching the hypothesis and conclusion of a conditional statemens is the converse of the original statement.
   Example:
      If I originally say "If there is a semi on the road then it will be load" then the converse would be 
      "If it is loud then there is a semi on the road"
   Test Question:
      Is it possible to have a true statement whos converse is also true?


inverse
   Definition:
      An immediate inference made from another conditional sentance.
   Explanation:
      Negating both the hypothesis and conclusion of a conditional statement.
   Example: 
      If I say "The sun is out therefore it is hot" then the inverse would be "The sun is not out therefore
      it is not hot".
   Test Question:
      Can you think of a true statement in which its inverse is also true?


R: real numbers
   Definition:
       Real are any numbers which fall into the following groups: whole numbers, rational numbers, and irrational numbers.
       Note that this excludes imaginary numbers and infinity. These are not real numbers.
    Example/Explanation:
       5, 17.65, -.54, 1/3, pi, sqrt(3)
    Test Questiton:
       Why are real numbers useful to us, where imaginary numbers aren't?


Z: integers
   Definition:
      Integers are numbers without a ratio.
   Explanation/example:
      These are just whole numbers. Things like 3, 56, 743, 12, 56, -7, -523 etc.
   Test Question:
      How many integers are there? Is this number also an integer?  


Q: rational numbers
   Definition:
      Rational numbers are numbers which include a ratio.
   Explanation/example:
      You can get a rational number by dividing two integers. For example 1/2, 1/3, 1/9.
   Test Question:
      Give three examples of irrational numbers.

predicate
   Definition:
      A boolean-valued function.
   Explanation:
      Think of it as a statement that may be true or false depending on the values of its variables.
   Example:
      An isEmpty function in a vector class.
   Test Question:
      When would you use a predicate?

Domain
   Definition:
      The complete set of possible values of the independent variable.
   Explanation:
      The set of all possible x-values which will make the function output real y-values.
   Examples:
      f(x) = x^2 - 2x + 5 domain = (-infinity, infinity)
   Test Question:
      What is the domain of the function f(x) = sqrt(x + 5)


CoDomain
   Definition:
      The set of all possible output values of a function.
   Explanation/Example:
      f(x) = 2x + 1
      therefore our codomain is 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 etc...
   Test Question:
      What is the difference between the Codomain and the range?


quantifier
   Definiton:
      Specifies the quantity of specimens in the domain of discourse that satisfy an open formula.
   Explanation/Example:
      Common quantifiers include phrases like "for all" and "there exists".
   Test Question:
      Why are quantifiers important when doing reasearch? 


antecedent
   Definition:
      The first half of a conditional statement.
   Explanation/Example:
      If P then Q...
      P would be the antecednet in this cacse.
   Test Question:
      Identify the antecednet in this statement: "There was a threat down the hall; when i make eye conntact
      i will strike."


consequent
   Definition:
      The second half of a conditional statement.
   Explanation/Example:
      If P then Q...
      Q is the consequent in this statement.
   Test Question:
      What is the consequent of stealing money from your mom's wallet? 


Set
   Definition:
      A collection of distinct objects.
   Explanation:
      These objects could be integers, rational numbers, shapes, or other collections of objects.
   Example:
      [1, 2, 4], [orange, blue, yellow], [c, b, g]
   Test Question:
      Why is this not considered a set: [4, 2, 3, 5, 6, 1, 7, 5, 4, 5, 6, 7, 8]


Fallacy
   Definition:
      An incorrect result arrived at by apparently correct, though actually specious reasoning.
   Explanation:
      A seemingly correct statement at first, but does not hold up under closer inspection.
   Example:
      

biconditional
   Definition:
      A statement that is true when both parts have the same truth value.
   Explanation/example:
      Typically biconditional statements will include the phrase "if and only if" For example 
      p = The weather is nice and sunny
      q = There are no clouds out
      So p <-> q would be The weather is nice and sunny if and only if there are no clouds out.
   Test Question:
      P = "Rock music is louc"
      Q = "People want to hear loud sounds"
      What is P <-> Q?
   

sufficient condition
   Definition:
     A condition which, if true, guarantees that a result is also true.
   Example/Explanation:
     If p implies q then knowing that p is true is enough evidence to conclude that q is also true. The roads
     are backed up, so it must be rush hour.
   Test Question:
     Give one example of a sufficient example you see in everyday life. 

necessary condition
   Definition:
      A condition which, if true, does not garuntee that a result is also true.
   Example/Explanation:
      If not p implies not q then knowing that p is false is not enough that to conclude that q is also false.
   Test Question:
      [explative deleted]


~p
   Identify:
      Negation
   Definition:
      The opposite of a statement.
   Example/Explanation:
      If a statement is true thenthe negation of that statement is false. For example if I say "it is sunny" the 
      negation would be "it is not sunny".


p ^ q
   Identify: 
      And operation
   Definition:
      Evaluates to true if both statements are true.
   Example/Explanation:
      A truth table is a good way to illustrate this
      p | q | p ^ q
      1   1     1
      1   0     0
      0   1     0
      1   0     0
      0   0     0


p V q
   Identify:
      Or operation
   Definition:
      Evaluates to true if one or both of the conditions are true.
   Example/Explanation:
   p | q | p V q
   1   1     1
   1   0     1
   0   1     1
   0   0     0


p XOR q
   Identify: 
      Xor operator
   Definition:
      Evaluates to true if one of the conditions is true but not both.
   Example/Explanation:
   p | q | p XOR q
   1   1      0
   1   0      1
   0   1      1
   0   0      0


p == q
   Identify:
     Equality operator
   Definition: 
     Evaluates to true if both pieces are the same and false if they are not
   Example/Explanation:
     p = 1
     q = 1
    (p == q) = 1
    
    p = 0
    p = 1
   (p == q) = 0


p -> q
   Identify:
      Conditional operator.
   Definition:
      Represents an if then relationship
   Example/Explanation:
      p = it is raining
      q = the grass is wet
      p -> q = if it is raining then the grass is wet


p <--> q
   Identify:
      Biconditional operator
   Definition:
      evaluates to true whenever both parts have the same truth value
   Example/Explanation:
    
   p | q | p <-> q
   1   1      1
   1   0      0
   0   1      0
   0   0      1


Three dots in a triangle
   Identify: 
      Therefore sign
   Definition:
      In logical proofs it is used to state the consequence of some premise.
   Example/Explanation:
      p ^ q therefore p


upside down A
   Identify: 
      universal quantifier
   Definiton: 
      translates to "for all"
   Explanation:
      In a logical statement this means that for all instances of some variable the following is true.
   Example:
      For all S such that s does not equal q.


Backwards E
   Identify: 
      Extensential quantifier
   Definition:
      translates to "for at least one instance of"
   Explanation:
      IN a logical statement this means that there exists at least one instance of the variable where the following is true.
   Example:
      For one instance of s such that s does not equal q.


union
   Definition:
      For two sets A and B the union is the set of elements which are in A, in B, or in both A and B.
   Example/Explanation:
      A = {5, 3, 4}
      B = {1, 4, 2, 8}
      A union B = {1, 2, 3, 4, 5, 8}


intersection
   Definition:
      For two sets A and B the intersection is the set of elements which are found in both A and B
   Example/Explanation:
      A = {4, 6, 7, 3, 1}
      B = {7, 9, 3, 10}
      A intersection B = {3, 7}


Commutative laws
   Definition:
      The result of addition and multiplication operations will be the same regardless of order.
   Example/Explanation:
       a + b = b + a and ab = ba


associative laws
   Definition:
       With addition and multiplication operations the terms can be associated in any way.
    Explanation/Example:
       (a + b) + c = a + (b + c)


distributive laws
    Definition:
        The law that relates addition and multiplication
     Example/Explanation:
        a(b + c) = ab + ac


identity laws
   Definition:
      When a set is anded to a tatuology or ored with a contradiction it results in the variable by itself.
   Example/Explanation:
      p ^ T = p
      p V F = p


negation laws
    Definition:
       A statement ored with its negation results in a statement that is always true and vice versa.
    Example/Explanation:
       p V !p = T
       p ^ !p = F


double negative law
    Definition:
       A statement that is negated twice results in the bare statement.
    Example/Explanation:
       !(!p) = p


idempotent laws
   Definition:
      A statement ored with itself is itself and vice versa
   Example/Explanation:
      p ^ p = p
      p V p = p


universal bound laws
   Definiton: 
      Statement ored with a tatuology is always true and vice versa
   Example/Explanation:
      p V T = T


De morgan's laws
   Definition:
      A negation can be distrubed as long as the sign is flipped.
   Example/Explanation:
      ~(p ^ q) = ~p V ~q


absorption laws
   Definition:
      A statement can be simplified by performing a redundent operation.
   Example/Explanation:
      p V (p ^ q) = p


negations of t and c


vacuously true
   Definition:
      Asserts that all members of the emtpy set have certain properties. 
   Example/Explanation:
      The statement "all phones in the room are turned off" when they are no cell phones in the room.

Modus Ponens
   Definition:
      Method of affirming
   Example/Explanation:
      if p then q
         p
      Therefore q


Modus Tollens
   Definition:
      Mode that denies by denying
   Example/Explanation:
      if p then q
      ~q
      therefore ~p

Elimination: valid argument form

Transitivity: Valid Argument form
