#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!



Contrapositive
   Definition:
      A proposition formed by contradicting both the subject and predicate or both the hypothesis and conclusion
      of a given proposition or theorem and interchanging them.
   Explanation:
      To find the contrapositive switch the hyptothesis and conclusion of a conditional statement and negating both.
   Example:
      If I first say "If it is raining then the grass is wet" then the contrapositive is 
      "If the grass is not wet then it is not raining".
   Test Question:
      If a statement is true is the contrapositive also true? And vice versa? 


Converse
   Definition:
      A converse is the result of reverseing a conditional statements two parts.
   Explanation:
      Switching the hypothesis and conclusion of a conditional statemens is the converse of the original statement.
   Example:
      If I originally say "If there is a semi on the road then it will be load" then the converse would be 
      "If it is loud then there is a semi on the road"
   Test Question:
      Is it possible to have a true statement whos converse is also true?


inverse
   Definition:
      An immediate inference made from another conditional sentance.
   Explanation:
      Negating both the hypothesis and conclusion of a conditional statement.
   Example: 
      If I say "The sun is out therefore it is hot" then the inverse would be "The sun is not out therefore
      it is not hot".
   Test Question:
      Can you think of a true statement in which its inverse is also true?


R: real numbers
   Definition:
       Real are any numbers which fall into the following groups: whole numbers, rational numbers, and irrational numbers.
       Note that this excludes imaginary numbers and infinity. These are not real numbers.
    Example/Explanation:
       5, 17.65, -.54, 1/3, pi, sqrt(3)
    Test Questiton:
       Why are real numbers useful to us, where imaginary numbers aren't?


Z: integers
   Definition:
      Integers are numbers without a ratio.
   Explanation/example:
      These are just whole numbers. Things like 3, 56, 743, 12, 56, -7, -523 etc.
   Test Question:
      How many integers are there? Is this number also an integer?  


Q: rational numbers
   Definition:
      Rational numbers are numbers which include a ratio.
   Explanation/example:
      You can get a rational number by dividing two integers. For example 1/2, 1/3, 1/9.
   Test Question:
      Give three examples of irrational numbers.

predicate
   Definition:
      A boolean-valued function.
   Explanation:
      Think of it as a statement that may be true or false depending on the values of its variables.
   Example:
      An isEmpty function in a vector class.
   Test Question:
      When would you use a predicate?

Domain
   Definition:
      The complete set of possible values of the independent variable.
   Explanation:
      The set of all possible x-values which will make the function output real y-values.
   Examples:
      f(x) = x^2 - 2x + 5 domain = (-infinity, infinity)
   Test Question:
      What is the domain of the function f(x) = sqrt(x + 5)


CoDomain
   Definition:
      The set of all possible output values of a function.
   Explanation/Example:
      f(x) = 2x + 1
      therefore our codomain is 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 etc...
   Test Question:
      What is the difference between the Codomain and the range?


quantifier
   Definiton:
      Specifies the quantity of specimens in the domain of discourse that satisfy an open formula.
   Explanation/Example:
      Common quantifiers include phrases like "for all" and "there exists".
   Test Question:
      Why are quantifiers important when doing reasearch? 


antecedent
   Definition:
      The first half of a conditional statement.
   Explanation/Example:
      If P then Q...
      P would be the antecednet in this cacse.
   Test Question:
      Identify the antecednet in this statement: "There was a threat down the hall; when i make eye conntact
      i will strike."


consequent
   Definition:
      The second half of a conditional statement.
   Explanation/Example:
      If P then Q...
      Q is the consequent in this statement.
   Test Question:
      What is the consequent of stealing money from your mom's wallet? 


Set
   Definition:
      A collection of distinct objects.
   Explanation:
      These objects could be integers, rational numbers, shapes, or other collections of objects.
   Example:
      [1, 2, 4], [orange, blue, yellow], [c, b, g]
   Test Question:
      Why is this not considered a set: [4, 2, 3, 5, 6, 1, 7, 5, 4, 5, 6, 7, 8]


Fallacy
   Definition:
      An incorrect result arrived at by apparently correct, though actually specious reasoning.
   Explanation:
      A seemingly correct statement at first, but does not hold up under closer inspection.
   Example:
      

biconditional
   Definition:
      A statement that is true when both parts have the same truth value.
   Explanation/example:
      Typically biconditional statements will include the phrase "if and only if" For example 
      p = The weather is nice and sunny
      q = There are no clouds out
      So p <-> q would be The weather is nice and sunny if and only if there are no clouds out.
   Test Question:
      P = "Rock music is louc"
      Q = "People want to hear loud sounds"
      What is P <-> Q?
   

sufficient condition
   Definition:
     A condition which, if true, guarantees that a result is also true.
   Example/Explanation:
     If p implies q then knowing that p is true is enough evidence to conclude that q is also true. The roads
     are backed up, so it must be rush hour.
   Test Question:
     Give one example of a sufficient example you see in everyday life. 

necessary condition
   Definition:
      A condition which, if true, does not garuntee that a result is also true.
   Example/Explanation:
      If not p implies not q then knowing that p is false is not enough that to conclude that q is also false.
   Test Question:
      [explative deleted]


~p
   Identify:
      Negation
   Definition:
      The opposite of a statement.
   Example/Explanation:
      If a statement is true thenthe negation of that statement is false. For example if I say "it is sunny" the 
      negation would be "it is not sunny".


p ^ q
   Identify: 
      

p V q

p XOR q

p == q

p -> q

p <--> q

Three dots in a triangle

upside down A

Backwards E

union

intersection

Commutative laws

associative laws

distributive laws

identity laws

negation laws

double negative law

idempotent laws

universal bound laws

De morgan's laws

absorption laws

negations of t and c

vacuously true

Modus Ponens

Modus Tollens

Elimination: valid argument form

Transitivity: Valid Argument form
